name: 'infrastructure'
description: 'Deploy Infrastructure'
inputs:
  DATABASE_URL:
    description: 'The URL of the store of infrastructure configuration'
    required: true
  EMAIL:
    description: 'The account to use to connect to the provider'
    required: true
  API_KEY:
    description: 'The key to use to connect to the provider'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    WORKING_DIR: ${{ inputs.WORKING_DIR }}
    DATABASE_URL: ${{ inputs.DATABASE_URL }}
    EMAIL: ${{ inputs.EMAIL }}
    API_KEY: ${{ inputs.API_KEY }}
    APP_NAME: ${{ inputs.APP_NAME }}