version: "3.8"
services:
  sudoku-infra:
    build:
      context: .
    image: sudoku-infra:latest
    environment:
      - WORKING_DIR=.
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL=${EMAIL}
      - API_KEY=${API_KEY}
