name: build-and-deploy-java
on:
  push:
    branches: [ main ]
    paths:
    - 'server-java/**'
    - 'ui/**'
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    env:
      SERVER_DIR: ./server-java
      UI_DIR: ./ui
    steps:
      - 
        name: Checkout The Code
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build And Push The UI Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.UI_DIR }}
          file: ./Dockerfile
          push: true
          tags: |
            adlardco/sudoku-ui:latest
      - 
        name: Login To Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.API_KEY }}
        run: heroku container:login
      - 
        name: Build And Push The Server Image
        env:
          HEROKU_API_KEY: ${{ secrets.API_KEY }}
        run: heroku container:push -a ${{ secrets.APP_NAME }} web 
        working-directory: ${{ env.SERVER_WORKING_DIR }}
      - 
        name: Release The Server
        env:
          HEROKU_API_KEY: ${{ secrets.API_KEY }}
        run: heroku container:release -a ${{ secrets.APP_NAME }} web
        working-directory: ${{ env.SERVER_WORKING_DIR }}