name: Build The UI Docker Image
on:
  push:
    branches: [ main ]
    paths:
    - 'ui/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      UI_DIR: ./ui
    steps:
      - 
        name: Checkout The Code
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build And Push The UI Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.UI_DIR }}
          file: ${{ env.UI_DIR }}/Dockerfile
          push: true
          tags: |
            adlardco/sudoku-ui:latest