name: infra
on:
  workflow_dispatch:    
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: infra
      uses: ./
      id: infra
      with:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        EMAIL: ${{ secrets.EMAIL }}
        API_KEY: ${{ secrets.API_KEY }}