name: infra
on:
  workflow_dispatch:    
jobs:
  infra:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: infra
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: infra
      uses: ./infra
      id: infra
      with:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        EMAIL: ${{ secrets.EMAIL }}
        API_KEY: ${{ secrets.API_KEY }}
