name: Deploy The Infrastructure
on:
  workflow_dispatch:    
jobs:
  infrastructure:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - 
      name: Deploy The Infrastructure
      id: infra
      uses: ./infra
      with:
        WORKING_DIR: ./infra
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        EMAIL: ${{ secrets.EMAIL }}
        API_KEY: ${{ secrets.API_KEY }}
        APP_NAME: ${{ secrets.APP_NAME }}